name: Обновление активностей

on:
  workflow_dispatch:
  schedule:
    - cron: '30 5 * * *'

jobs:
  update-dates:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.DOKA_BOT_ACCESS_TOKEN }}
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.DOKA_BOT_ACCESS_TOKEN }}
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Обновление информации о репозитории
        run: |
          source .env
          mkdir issues
          for I in $(seq 1 $PAGE_COUNT); do
            echo ">>>>>> Запрос $I из $PAGE_COUNT:"
            curl --request GET  \
              --header "Accept: application/vnd.github+json" \
              --header "Authorization: Bearer $GITHUB_TOKEN" \
              --header "X-GitHub-Api-Version: 2022-11-28" \
              https://api.github.com/repos/doka-guide/content/issues\?state\=all\&per_page\=$ITEM_COUNT\&page\=$I >> issues/issues.$I.json
          done
          node issues.js
          rm -rf issues
      - name: Создание коммита с обновлениями полей
        run: |
          if [[ -z $(git status -s) ]]
          then
            echo $(git status)
          else
            git config user.name "Doka Dog"
            git config user.email "<hi@doka.guide>"

            git add "./issues.json"
            git commit -m "Обновляет информацию о репозитории" --author "Doka Dog <hi@doka.guide>"

            git pull --rebase
            git push origin main

            exit
          fi
